import {
  getResourceDie,
  isResourceItem,
  localize,
  rollResourceDie
} from "./resource-service.js";

const ROW_SELECTOR = [
  ".fblqa-gear-card[data-item-id]",
  "tr.item[data-item-id]",
  ".item[data-item-id]",
  ".item[data-itemid]",
  "[data-item-id].item",
  "[data-itemid].item"
].join(", ");

const sheetStates = new WeakMap();

export function renderResourceActorSheet(app, htmlOrElement) {
  const actor = app?.actor ?? app?.document;
  if (!actor || actor.documentName !== "Actor" || actor.type !== "character") return;

  const root = extractElement(htmlOrElement) ?? extractElement(app?.element);
  if (!root) return;

  const state = ensureSheetState(root, actor);
  state.actor = actor;

  const gearTab = findGearTab(root);
  if (!gearTab) return;

  bindGearObserver(state, gearTab);

  // A normal Foundry render can replace most of the sheet DOM in one pass.
  // Decorate that completed DOM once and discard observer records generated by
  // the same render. Mutations that happen later (notably Quick Access card
  // generation) are still observed incrementally.
  decorateGearTab(gearTab, actor);
  state.observer?.takeRecords();
}

export function closeResourceActorSheet(app) {
  const root = extractElement(app?.element);
  if (!root) return;

  const state = sheetStates.get(root);
  if (!state) return;

  state.observer?.disconnect();
  root.removeEventListener("click", state.onClick, true);
  sheetStates.delete(root);
}

function ensureSheetState(root, actor) {
  const existing = sheetStates.get(root);
  if (existing) return existing;

  const state = { actor, observer: null, observedGearTab: null, onClick: null };

  state.onClick = (event) => {
    if (!(event.target instanceof Element)) return;
    const badge = event.target.closest(".fblr-resource-badge[data-fblr-resource-item-id]");
    if (!(badge instanceof HTMLButtonElement) || !root.contains(badge)) return;

    event.preventDefault();
    event.stopPropagation();

    const item = state.actor?.items?.get?.(badge.dataset.fblrResourceItemId);
    if (!isResourceItem(item) || badge.disabled) return;

    badge.disabled = true;
    void rollResourceDie(item).catch((error) => {
      console.error("fbl-resource-dice | inventory resource roll failed", error);
      ui.notifications?.error?.(localize("Notifications.RollFailed", "Resource roll failed."));
    }).finally(() => {
      if (badge.isConnected) badge.disabled = false;
    });
  };

  root.addEventListener("click", state.onClick, true);
  sheetStates.set(root, state);
  return state;
}

function bindGearObserver(state, gearTab) {
  const quickAccessActive = game.modules?.get?.("fbl-quick-access")?.active === true;
  if (!quickAccessActive) {
    state.observer?.disconnect();
    state.observer = null;
    state.observedGearTab = null;
    return;
  }

  if (state.observer && state.observedGearTab === gearTab) return;
  state.observer?.disconnect();

  state.observer = new MutationObserver((mutations) => {
    // Only the Gear tab is observed. Quick Access builds complete rows/cards
    // before inserting them, so decorating added subtrees is enough and our
    // own badge insertion cannot feed the observer back into a full rescan.
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        if (!(node instanceof Element)) continue;
        decorateAddedSubtree(node, state.actor);
      }
    }
    // Discard records produced only by the badges inserted above. Without this
    // the browser would schedule one harmless extra observer callback per batch.
    state.observer?.takeRecords();
  });
  state.observedGearTab = gearTab;
  state.observer.observe(gearTab, { childList: true, subtree: true });
}

function decorateGearTab(gearTab, actor) {
  for (const row of gearTab.querySelectorAll(ROW_SELECTOR)) {
    decorateRow(row, actor);
  }
}

function decorateAddedSubtree(node, actor) {
  if (node.matches?.(".fblr-resource-badge, .fblr-resource-badge *")) return;

  if (node.matches?.(ROW_SELECTOR)) decorateRow(node, actor);
  for (const row of node.querySelectorAll?.(ROW_SELECTOR) ?? []) {
    decorateRow(row, actor);
  }
}

function decorateRow(row, actor) {
  if (!(row instanceof HTMLElement)) return;
  if (!row.closest('.gear-tab, .tab[data-tab="gear"]')) return;
  if (row.closest(".fblqa-panel")) return;

  const itemId = row.dataset.itemId ?? row.dataset.itemid;
  const item = itemId ? actor.items?.get?.(itemId) : null;

  const isCard = row.classList.contains("fblqa-gear-card");
  const target = isCard
    ? row.querySelector(".fblqa-gear-card-top")
    : row.querySelector("td.profile > div, .profile > div, .item-name");
  if (!(target instanceof HTMLElement)) return;

  let badge = target.querySelector(":scope > .fblr-resource-badge");
  if (!isResourceItem(item)) {
    badge?.remove();
    return;
  }

  if (!badge) {
    badge = buildBadge(item, isCard);
    if (isCard) {
      target.prepend(badge);
    } else {
      const name = target.querySelector(":scope > .name, :scope > .item-name");
      if (name) target.insertBefore(badge, name);
      else target.append(badge);
    }
  }

  updateBadge(badge, getResourceDie(item), isCard);
}

function buildBadge(item, compact) {
  const button = document.createElement("button");
  button.type = "button";
  button.classList.add("fblr-resource-badge");
  if (compact) button.classList.add("fblr-resource-badge-compact");
  button.dataset.fblrResourceItemId = item.id;

  const icon = document.createElement("i");
  icon.classList.add("fas", "fa-dice-d6");
  icon.setAttribute("aria-hidden", "true");

  const value = document.createElement("span");
  value.classList.add("fblr-resource-badge-value");
  button.append(icon, value);
  return button;
}

function updateBadge(badge, die, compact) {
  badge.classList.toggle("fblr-resource-badge-compact", compact);

  const value = badge.querySelector(".fblr-resource-badge-value");
  const nextValue = compact ? String(die) : `d${die}`;
  if (value && value.textContent !== nextValue) value.textContent = nextValue;

  const title = localize("Actions.UseDie", "Use resource (d{die})", { die });
  if (badge.title !== title) badge.title = title;
  if (badge.getAttribute("aria-label") !== title) badge.setAttribute("aria-label", title);
}

function findGearTab(root) {
  return root.querySelector('.gear-tab, .tab[data-tab="gear"]');
}

function extractElement(value) {
  if (value instanceof HTMLElement) return value;
  if (value?.[0] instanceof HTMLElement) return value[0];
  if (value?.element instanceof HTMLElement) return value.element;
  return null;
}
